export const AUTH = 'AUTH';
export const SELECTED_AUCTION_RAFFLE_ITEM = 'SELECTED_AUCTION_RAFFLE_ITEM';
export const SELECTED_STORE_ITEM = 'SELECTED_STORE_ITEM';
export const SELECTED_RAFFLE_ITEM = 'SELECTED_RAFFLE_ITEM';
